// ──────────────────────────────────────────────────────────────
// A very small PDF writer.
//
// Why not a library. This project has four runtime dependencies — next, react,
// react-dom and Neon's driver — and PR 2.1 treated adding the fourth as a
// supply-chain decision worth a paragraph. The PDF options are worse than that
// trade suggests: headless Chrome is far past Vercel's function size limit, and
// the lighter renderers still pull tens of megabytes of font and layout code to
// produce what this report actually needs, which is text in two weights, filled
// rectangles and rules.
//
// The other half of the reason is that a PDF is the *second* serialisation of a
// scan report, and PR 2.3 spent its whole length making the first one safe. A
// generator whose output nobody can inspect would be a second way to leak the
// prompts. Everything here is plain, uncompressed PDF 1.4, so
// `scripts/verify-report.ts` can search the generated bytes for a withheld
// prompt the same way `verify-paywall.ts` searches the JSON.
//
// Scope, deliberately: the base-14 fonts (Helvetica and Helvetica-Bold), which
// every reader has and which therefore need no embedding; WinAnsi text;
// rectangles and lines. No images, no transparency, no compression. That is the
// whole feature set the report uses.
// ──────────────────────────────────────────────────────────────

export type FontName = "regular" | "bold";

/** A4 in PostScript points, the unit PDF measures in. */
export const PAGE_WIDTH = 595.28;
export const PAGE_HEIGHT = 841.89;

// ── Font metrics ─────────────────────────────────────────────────────────
//
// Widths in 1/1000 em for ASCII 32–126, from the Adobe AFM files for the
// base-14 fonts. Only the printable ASCII range is carried: it is what the
// report contains after transliteration, and a full 256-entry table would be
// mostly zeroes. Anything outside the range measures as 500, which is close
// enough for the wrapping decision and never wrong in a way a reader sees.

const HELVETICA = [
  278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278,
  556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556,
  1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778,
  667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556,
  333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556,
  556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584,
];

const HELVETICA_BOLD = [
  278, 333, 474, 556, 556, 889, 722, 238, 333, 333, 389, 584, 278, 333, 278, 278,
  556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 333, 333, 584, 584, 584, 611,
  975, 722, 722, 722, 722, 667, 611, 778, 722, 278, 556, 722, 611, 833, 722, 778,
  667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 333, 278, 333, 584, 556,
  333, 556, 611, 556, 611, 556, 333, 611, 611, 278, 278, 556, 278, 889, 611, 611,
  611, 611, 389, 556, 333, 611, 556, 778, 556, 556, 500, 389, 280, 389, 584,
];

/**
 * Replace characters a WinAnsi reader would render as a box.
 *
 * The site copy is full of typographic punctuation — em dashes, curly quotes,
 * ellipses — because it reads better on a web page. In a PDF an unmapped
 * character is not an error, it is a wrong glyph or a blank, which looks like a
 * broken document rather than a missing feature. Mapping them to ASCII is the
 * one transformation that is invisible to the reader.
 */
export function toAscii(text: string): string {
  return text
    .replace(/[‘’‚′]/g, "'")
    .replace(/[“”„″]/g, '"')
    .replace(/[–—―]/g, "-")
    .replace(/…/g, "...")
    .replace(/ /g, " ")
    .replace(/[•·]/g, "-")
    .replace(/→/g, "->")
    .replace(/≤/g, "<=")
    .replace(/≥/g, ">=")
    // Anything still outside printable ASCII becomes '?' rather than silently
    // producing a glyph the width table did not measure.
    .replace(/[^\x20-\x7E\n]/g, "?");
}

/** Width of `text` in points at `size`, for wrapping and centring. */
export function textWidth(text: string, font: FontName, size: number): number {
  const table = font === "bold" ? HELVETICA_BOLD : HELVETICA;
  let total = 0;
  for (const ch of toAscii(text)) {
    const code = ch.charCodeAt(0);
    total += code >= 32 && code <= 126 ? table[code - 32] : 500;
  }
  return (total * size) / 1000;
}

/**
 * Break `text` into lines that fit `maxWidth`.
 *
 * A word longer than the line — a URL, an API key in an evidence field — is
 * hard-split rather than allowed to run off the page. Evidence is exactly where
 * long unbroken strings occur, so this is the common case, not the edge.
 */
export function wrapText(
  text: string,
  font: FontName,
  size: number,
  maxWidth: number,
): string[] {
  const lines: string[] = [];

  for (const paragraph of toAscii(text).split("\n")) {
    let line = "";
    for (const word of paragraph.split(/\s+/).filter(Boolean)) {
      const candidate = line ? `${line} ${word}` : word;
      if (textWidth(candidate, font, size) <= maxWidth) {
        line = candidate;
        continue;
      }
      if (line) {
        lines.push(line);
        line = "";
      }
      if (textWidth(word, font, size) <= maxWidth) {
        line = word;
        continue;
      }
      let chunk = "";
      for (const ch of word) {
        if (textWidth(chunk + ch, font, size) > maxWidth) {
          lines.push(chunk);
          chunk = "";
        }
        chunk += ch;
      }
      line = chunk;
    }
    lines.push(line);
  }

  // A trailing empty line is a blank paragraph the caller did not ask for.
  while (lines.length > 1 && lines[lines.length - 1] === "") lines.pop();
  return lines;
}

/** Escape for a PDF literal string. */
export function escapeText(text: string): string {
  return toAscii(text)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

/** `#rrggbb` to the 0–1 components PDF wants. */
export function rgb(hex: string): Rgb {
  const value = hex.replace("#", "");
  return {
    r: parseInt(value.slice(0, 2), 16) / 255,
    g: parseInt(value.slice(2, 4), 16) / 255,
    b: parseInt(value.slice(4, 6), 16) / 255,
  };
}

function fmt(n: number): string {
  // Three decimals is beyond the precision of any renderer at these sizes, and
  // trimming keeps the content stream searchable by eye.
  return Number(n.toFixed(3)).toString();
}

/** One page's content stream, built up by the document. */
class Page {
  readonly ops: string[] = [];
}

export class PdfDocument {
  private readonly pages: Page[] = [];
  private current: Page | null = null;

  addPage(): void {
    this.current = new Page();
    this.pages.push(this.current);
  }

  get pageCount(): number {
    return this.pages.length;
  }

  private page(): Page {
    if (!this.current) this.addPage();
    return this.current as Page;
  }

  /**
   * Draw onto an already-finished page.
   *
   * Footers need the total page count ("2 of 5"), which is not known until the
   * last page exists. Rather than guess, or lay the document out twice, the
   * caller comes back at the end and writes each footer with the real number.
   */
  onPage(index: number, draw: (doc: PdfDocument) => void): void {
    const previous = this.current;
    this.current = this.pages[index];
    try {
      draw(this);
    } finally {
      this.current = previous;
    }
  }

  /**
   * Draw one line of text.
   *
   * `y` is measured from the top of the page, because a report is laid out
   * downwards and PDF's origin is bottom-left. Doing the flip here rather than
   * at every call site removes an entire class of upside-down-layout mistake.
   */
  text(
    content: string,
    x: number,
    y: number,
    options: { font?: FontName; size?: number; color?: Rgb } = {},
  ): void {
    const { font = "regular", size = 10, color } = options;
    const ops = this.page().ops;
    if (color) ops.push(`${fmt(color.r)} ${fmt(color.g)} ${fmt(color.b)} rg`);
    ops.push(
      "BT",
      `/${font === "bold" ? "F2" : "F1"} ${fmt(size)} Tf`,
      `${fmt(x)} ${fmt(PAGE_HEIGHT - y)} Td`,
      `(${escapeText(content)}) Tj`,
      "ET",
    );
    if (color) ops.push("0 0 0 rg");
  }

  /** Filled rectangle. `y` is the top edge. */
  rect(x: number, y: number, width: number, height: number, color: Rgb): void {
    this.page().ops.push(
      `${fmt(color.r)} ${fmt(color.g)} ${fmt(color.b)} rg`,
      `${fmt(x)} ${fmt(PAGE_HEIGHT - y - height)} ${fmt(width)} ${fmt(height)} re`,
      "f",
      "0 0 0 rg",
    );
  }

  /** Horizontal rule. */
  line(x1: number, y: number, x2: number, color: Rgb, width = 0.5): void {
    this.page().ops.push(
      `${fmt(color.r)} ${fmt(color.g)} ${fmt(color.b)} RG`,
      `${fmt(width)} w`,
      `${fmt(x1)} ${fmt(PAGE_HEIGHT - y)} m`,
      `${fmt(x2)} ${fmt(PAGE_HEIGHT - y)} l`,
      "S",
      "0 0 0 RG",
    );
  }

  /**
   * Serialise the document.
   *
   * The xref table holds a byte offset for every object, so the file is
   * assembled as buffers with a running offset rather than as a string — a
   * multi-byte character anywhere earlier would otherwise put every subsequent
   * offset out by the difference between characters and bytes, and produce a
   * file that opens in a forgiving reader and fails in a strict one.
   */
  build(): Buffer {
    if (this.pages.length === 0) this.addPage();

    const chunks: Buffer[] = [];
    const offsets: number[] = [];
    let position = 0;

    const push = (text: string) => {
      const buffer = Buffer.from(text, "latin1");
      chunks.push(buffer);
      position += buffer.length;
    };

    const pushObject = (id: number, body: string) => {
      offsets[id] = position;
      push(`${id} 0 obj\n${body}\nendobj\n`);
    };

    push("%PDF-1.4\n");

    // 1 catalog, 2 page tree, 3 and 4 fonts, then a pair per page.
    const firstPageId = 5;
    const pageIds = this.pages.map((_, i) => firstPageId + i * 2);
    const contentIds = this.pages.map((_, i) => firstPageId + i * 2 + 1);

    pushObject(1, "<< /Type /Catalog /Pages 2 0 R >>");
    pushObject(
      2,
      `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${this.pages.length} >>`,
    );
    pushObject(
      3,
      "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    );
    pushObject(
      4,
      "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
    );

    this.pages.forEach((page, index) => {
      pushObject(
        pageIds[index],
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${fmt(PAGE_WIDTH)} ${fmt(PAGE_HEIGHT)}] ` +
          `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentIds[index]} 0 R >>`,
      );
      const stream = page.ops.join("\n");
      pushObject(
        contentIds[index],
        `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
      );
    });

    const objectCount = contentIds[contentIds.length - 1] + 1;
    const xrefAt = position;
    let xref = `xref\n0 ${objectCount}\n0000000000 65535 f \n`;
    for (let id = 1; id < objectCount; id += 1) {
      xref += `${String(offsets[id] ?? 0).padStart(10, "0")} 00000 n \n`;
    }
    push(xref);
    push(`trailer\n<< /Size ${objectCount} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`);

    return Buffer.concat(chunks);
  }
}
